name: Deploy Multi-language Books with Navigation

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '.github/workflows/deploy.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: [en, zh]   # 支持扩展
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.34"

      - name: Build ${{ matrix.lang }} book
        run: |
          cd docs/mdbook_${{ matrix.lang }}
          mdbook build --dest-dir ../../../book/${{ matrix.lang }}

      - name: Upload book artifact
        uses: actions/upload-artifact@v3
        with:
          name: book-${{ matrix.lang }}
          path: book/${{ matrix.lang }}

  deploy:
    runs-on: ubuntu-latest
    needs: build   # 依赖所有构建作业
    steps:
      - name: Download all book artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Reconstruct book directories
        run: |
          mkdir -p public
          # 将每个语言制品移动到public目录
          for lang in en zh; do
            if [ -d "artifacts/book-$lang" ]; then
              mv "artifacts/book-$lang" "public/$lang"
            fi
          done

      - name: Add navigation page
        run: |
          cp docs/index.html public/index.html
          # 如果有其他静态资源，也复制过来
          if [ -d "docs/assets" ]; then
            cp -r docs/assets public/
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: false        if: matrix.lang == 'en'
        run: |
          mkdir -p public/
          cp -r book/* public/ || echo "No build output"
          cp docs/index.html public/index.html
          #if [ -d ""]

          # 添加重定向首页（可选）
          # echo '<!DOCTYPE html><meta http-equiv="refresh" content="0; url=/en/">' > public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: false
